### ISSUE TITLE
Add new feature "rand_prime(m,n)", extending the "between(m,n)" function 

### ISSUE THREAD

**Issue by kadhirash** [nbcl/primality#15]
## Summary
rand_prime(m,n): Returns a random prime number within the range m,n.
## Expected Result

It would be great to have a feature that returns a random prime number between the range as we already have "between(m,n)" that returns all the prime numbers between the range m,n.

## Reproduction Steps

```python
from primality import primality
print(primality.rand_prime(2,50))
17
print(primality.rand_prime(2,50))
29
```

## System Information
Python 3.8.6
macOS Catalina 10.15.7

**Comment by nbcl** [comment]
**🎉 Thanks for your interest in contributing to Primality**

Hello @kadhirash! 

This is an interesting enhancement, but I'm having trouble figuring out how it could be implemented to fit every user's need.

A first approach could be achieved by using random.choice(), as follows.

```python
between = primality.between(2, 4000)
random.choice(between)
```

But this implementation may not suit some users, who require a more advanced source of randomness like [Secrets](https://docs.python.org/3.8/library/secrets.html), as follows.

```python
secrets.choice(between)
secrets.SystemRandom().choice(between)
```

From the above, I currently can't seem to point to any particular implementation as perfectly suiting for Primality, and would suggest users to be the ones in charge of choosing between them, reggarding their specific needs.

If you are certain about any of them (or any method that I could be missing), or can think of an implementation that could provide multiple options to fit different user needs, please let me know so we can discuss this further.

**Thank you!**

**Comment by kadhirash** [comment]
@nbcl I see, I don't know much about the "Secrets" functionality but I was leaning towards the first approach. Maybe there could be a way to have the user choose which random function they want (randomint or secrets) and the function will do that after.

**Comment by nbcl** [comment]
>Maybe there could be a way to have the user choose which random function they want (randomint or secrets) and the function will do that after.

Exactly @kadhirash! This can be achieved in different ways, such as, for example, using _default arguments_ to provide default values in the function's arguments.
