### ISSUE TITLE
Broken wiki link in README.md

### ISSUE THREAD

**Issue by chethansanna** [nbcl/primality#19]
Hi @nbcl,

The wiki page link from the README.md is not a valid one. Shall I link it to a proper wiki page of this repository?

![image](https://user-images.githubusercontent.com/47500198/111912882-d97e5100-8a6b-11eb-8bd3-0da2b2ede014.png)

**Thanks!**

_Originally posted by @chethansanna in https://github.com/nbcl/primality/issues/1#issuecomment-803617993_

**Comment by nbcl** [comment]
**🎉 Thanks for your interest in contributing to Primality**

Hello @chethansanna! 

> The wiki page link from the README.md is not a valid one.

You are right, for some reason, an incorrect link is associated with the wiki page.

> Shall I link it to a proper wiki page of this repository?

I would greatly appreciate if you do so!

**Thank you!**
