### ISSUE TITLE
Add new method to return all primes within a range(m,n) - Enhancement

### ISSUE THREAD

**Issue by loge1998** [nbcl/primality#5]
Summary.

## Expected Result

I am planing to implement this function using Sieve of Eratosthenes.

## Reproduction Steps

```python
from primality import primality

primality.list_all_primes_within_range(5,10)
>> [5,7]
```

**Comment by loge1998** [comment]
Can i start working on it?

**Comment by nbcl** [comment]
**🎉 Thanks for your interest in contributing to Primality**

Hello @loge1998! 

This is an interesting feature, but please note the following.

The correct implementation should add an extra optional parameter to the already existing ``prange()``, and not create a new function.

Apart from that, please also note that the suggested method, although fast for small numbers, would yield slower results when provided with a range of higher numbers, as follows.

```python
primality.list_all_primes_within_range(10000000,10000100)
```

A correct solution for the current state of the library would be using the currently implemented ``prange()`` together with ``isprime()`` to only test all non-even integers between the range.

**Thank you!**

**Comment by loge1998** [comment]
Ok I got it. Will start working on this Issue...

**Comment by IamShubhamGupto** [comment]
Has this already been assigned ? Is there anythign else I can contribute ?

**Comment by nbcl** [comment]
**🎉 Thanks for your interest in contributing to Primality**

Hello @IamShubhamGupto! 

> Has this already been assigned ?

Currently @loge1998 is working on this feature, you can check out and contribute to his implementation in #6!

> Is there anything else I can contribute ?

Primality is at an early stage, and there are many features that could be added. Issues and pull requests are open for your suggestions and enhancements! 

**Thank you!**

**Comment by nbcl** [comment]
**🎉 Merged:** Add between() to primality/primality.py (#6)
