### ISSUE TITLE
adding methods "nextprime(n)" and "prevprime(n)"

### ISSUE THREAD

**Issue by yonatanGal** [nbcl/primality#7]
## Summary

Hi! I have an idea for two new functions that can be added. both accepts an int n.
1. nextprime(n) - returns the next greater prime than n
2. prevprime(n) - returns the previous prime number smaller than n.

## Example

```python
from primality import primality
print(primality.nextprime(3))
5
print(primality.prevprime(7))
5
print(primality.nextprime(-100))
2
```

I would like to start working on those two functions. is it OK?

**Comment by nbcl** [comment]
**🎉 Thanks for your interest in contributing to Primality**

Hello @yonatanGal! 

This is an interesting feature, please feel free to begin development of it!

Finally, don't forget to open up two different pull requests for each one of the functions, and adding the corresponding changes to the documentation and examples in [docs/](docs/) and [README.md](README.md) respectively.

**Thank you!**

**Comment by yonatanGal** [comment]
Great, i'll start working on it!

**Comment by yonatanGal** [comment]
I sent a pull request, would love to know if you have any insights / suggestions :)

**Comment by nbcl** [comment]
🎉 **Merged:** Add nextprime() to primality/primality.py (#10)
