### ISSUE TITLE
Changes in Theory.md

### ISSUE THREAD

**Issue by Akshu-on-github** [nbcl/primality#8]
Hey there!

I'd like to make the following changes to the THEORY.md file :
- Markdown in the ordered list and superscript
- Add links to the papers mentioned
- Add a summary of each of the three theories

And in the README.md file, I'd like to:
- Reflect the changes in markdown
- Add a link to the THEORY.md file for more details

I think that this would add value to the project by way of documentation and thus, would like to create a PR on this issue...
I hope that's fine!

**Comment by nbcl** [comment]
**🎉 Thanks for your interest in contributing to Primality**

Hello @AkshayaKulasekaran! 

Documentation is a key aspect of every good library, please feel free to begin development of this enhancement!

Finally, I would suggest to keep all summaries short and concise, without extending further apart from a paragraph, as a user looking for a more in-depth understanding of the underlying theory could continue reading directly from the provided sources.

**Thank you!**

**Comment by Akshu-on-github** [comment]
Sure thing, @nbcl!
